# Set site.output == "epub"
output: "epub"
# Set site.image-set == "images/epub"
image-set: "images/epub"
# Turn off documentation and activate epub collection
collections:
  docs:
    output: false
  epub:
    output: true
exclude:
  # the usual excludes from _config.yml
  - run-linux.sh
  - run-mac.command
  - run-windows.bat
  - Gemfile
  - Gemfile.lock
  - README*
  - LICENSE*
  - CHANGELOG*
  # exclude files we don't need for epub
  - /*/styles/print-pdf.scss
  - /*/styles/screen-pdf.scss
  - /*/styles/web.scss
  - /*/styles/app.scss
  - /*/index.md
  - /*/images/print-pdf
  - /*/images/screen-pdf
  - /*/images/web
  - /*/images/app
  # Books ------------------
  # - adult-hiv
  # - breast-care
  # - catalogue
  # - child-healthcare
  # - childhood-critical-care
  # - childhood-hiv
  # - childhood-tb
  # - congenital-disorders
  # - ebola-prevention-and-control
  # - empathetic-care-a-guide-for-community-health-workers
  # - facilitators-guide
  # - fetal-heart-rate-handbook
  # - infection-prevention-and-control
  # - intrapartum-care
  # - maternal-care
  # - maternal-mental-health
  # - mother-and-baby-care-for-community-health-workers
  # - mother-and-baby-friendly-care
  # - newborn-care
  # - perinatal-hiv
  # - primary-maternal-care
  # - primary-newborn-care
  # - samples
  # - public-health
  # - saving-mothers-and-babies
  # - womens-health-care
  # ------------------------
# We deliberately empty the keep_files list here,
# so that files we don't want don't end up in the epub
# but not in the manifest.
keep_files: []
# Configure HTML compression. For epub, we need to compress
# to avoid invalid empty line at start of XML docs.
# See https://github.com/penibelst/jekyll-compress-html
compress_html:
  blanklines: false
# Map file extensions to media types for the opf
media-types:
  html: "application/xhtml+xml"
  xhtml: "application/xhtml+xml"
  css: "text/css"
  jpg: "image/jpeg"
  jpeg: "image/jpeg"
  gif: "image/gif"
  png: "image/png"
  svg: "image/svg+xml"
  ttf: "application/font-sfnt"
  otf: "application/font-sfnt"
  woff: "application/font-woff"
  woff2: "font/woff2"
  mp3: "audio/mpeg"
  mp4: "audio/mp4"
  ncx: "application/x-dtbncx+xml"
  txt: "text/plain"
  js: "application/x-javascript"
  unknown: "application/octet-stream"
